/**
 * @fileoverview Unit tests for OpenAPISchemaRegistry
 */

import {
  OpenAPISchemaRegistry,
  CommonSchemas,
  CommonSecuritySchemes,
} from '../../src/openapi/schemas';

describe('OpenAPISchemaRegistry', () => {
  beforeEach(() => {
    OpenAPISchemaRegistry.clear();
  });

  describe('registerSchema', () => {
    it('should register a single schema', () => {
      const schema = {
        type: 'object',
        properties: {
          id: { type: 'string' },
          name: { type: 'string' },
        },
      };

      OpenAPISchemaRegistry.registerSchema('User', schema);

      expect(OpenAPISchemaRegistry.hasSchema('User')).toBe(true);
      expect(OpenAPISchemaRegistry.getSchema('User')).toEqual(schema);
    });

    it('should overwrite existing schema with same name', () => {
      const schema1 = {
        type: 'object',
        properties: { old: { type: 'string' } },
      };
      const schema2 = {
        type: 'object',
        properties: { new: { type: 'string' } },
      };

      OpenAPISchemaRegistry.registerSchema('Test', schema1);
      OpenAPISchemaRegistry.registerSchema('Test', schema2);

      expect(OpenAPISchemaRegistry.getSchema('Test')).toEqual(schema2);
    });

    it('should register schema with metadata', () => {
      const schema = { type: 'object' };

      OpenAPISchemaRegistry.registerSchema('User', schema, {
        description: 'User entity',
        parent: 'BaseEntity',
        autoGenerated: true,
      });

      const def = OpenAPISchemaRegistry.getSchemaDefinition('User');
      expect(def?.description).toBe('User entity');
      expect(def?.parent).toBe('BaseEntity');
      expect(def?.autoGenerated).toBe(true);
    });
  });

  describe('registerSchemas', () => {
    it('should register multiple schemas at once', () => {
      const schemas = {
        User: { type: 'object', properties: { id: { type: 'string' } } },
        Post: { type: 'object', properties: { title: { type: 'string' } } },
        Comment: { type: 'object', properties: { text: { type: 'string' } } },
      };

      OpenAPISchemaRegistry.registerSchemas(schemas);

      expect(OpenAPISchemaRegistry.schemaCount).toBe(3);
      expect(OpenAPISchemaRegistry.hasSchema('User')).toBe(true);
      expect(OpenAPISchemaRegistry.hasSchema('Post')).toBe(true);
      expect(OpenAPISchemaRegistry.hasSchema('Comment')).toBe(true);
    });

    it('should handle empty object', () => {
      OpenAPISchemaRegistry.registerSchemas({});
      expect(OpenAPISchemaRegistry.schemaCount).toBe(0);
    });
  });

  describe('unregisterSchema', () => {
    it('should remove a registered schema', () => {
      OpenAPISchemaRegistry.registerSchema('User', { type: 'object' });
      expect(OpenAPISchemaRegistry.hasSchema('User')).toBe(true);

      const result = OpenAPISchemaRegistry.unregisterSchema('User');

      expect(result).toBe(true);
      expect(OpenAPISchemaRegistry.hasSchema('User')).toBe(false);
    });

    it('should return false for non-existent schema', () => {
      const result = OpenAPISchemaRegistry.unregisterSchema('NonExistent');
      expect(result).toBe(false);
    });
  });

  describe('getSchema', () => {
    it('should return undefined for non-existent schema', () => {
      expect(OpenAPISchemaRegistry.getSchema('NonExistent')).toBeUndefined();
    });

    it('should return the registered schema', () => {
      const schema = { type: 'string', format: 'email' };
      OpenAPISchemaRegistry.registerSchema('Email', schema);

      expect(OpenAPISchemaRegistry.getSchema('Email')).toEqual(schema);
    });
  });

  describe('getSchemaDefinition', () => {
    it('should return full schema definition with metadata', () => {
      OpenAPISchemaRegistry.registerSchema(
        'User',
        { type: 'object' },
        { description: 'User entity', parent: 'Base' },
      );

      const def = OpenAPISchemaRegistry.getSchemaDefinition('User');

      expect(def?.schema).toEqual({ type: 'object' });
      expect(def?.description).toBe('User entity');
      expect(def?.parent).toBe('Base');
    });

    it('should return undefined for non-existent schema', () => {
      expect(
        OpenAPISchemaRegistry.getSchemaDefinition('NonExistent'),
      ).toBeUndefined();
    });
  });

  describe('getAllSchemas', () => {
    it('should return empty object when no schemas registered', () => {
      expect(OpenAPISchemaRegistry.getAllSchemas()).toEqual({});
    });

    it('should return all registered schemas', () => {
      OpenAPISchemaRegistry.registerSchema('A', { type: 'string' });
      OpenAPISchemaRegistry.registerSchema('B', { type: 'number' });

      const all = OpenAPISchemaRegistry.getAllSchemas();
      expect(Object.keys(all)).toHaveLength(2);
      expect(all['A']).toEqual({ type: 'string' });
      expect(all['B']).toEqual({ type: 'number' });
    });
  });

  describe('getAllSchemaDefinitions', () => {
    it('should return all schema definitions with metadata', () => {
      OpenAPISchemaRegistry.registerSchema(
        'A',
        { type: 'string' },
        { description: 'Schema A' },
      );
      OpenAPISchemaRegistry.registerSchema('B', { type: 'number' });

      const all = OpenAPISchemaRegistry.getAllSchemaDefinitions();

      expect(all['A'].description).toBe('Schema A');
      expect(all['B'].schema).toEqual({ type: 'number' });
    });
  });

  describe('getChildSchemas', () => {
    it('should return schemas that inherit from a parent', () => {
      OpenAPISchemaRegistry.registerSchema('Base', { type: 'object' });
      OpenAPISchemaRegistry.registerSchema(
        'User',
        { type: 'object' },
        { parent: 'Base' },
      );
      OpenAPISchemaRegistry.registerSchema(
        'Admin',
        { type: 'object' },
        { parent: 'Base' },
      );
      OpenAPISchemaRegistry.registerSchema('Post', { type: 'object' });

      const children = OpenAPISchemaRegistry.getChildSchemas('Base');

      expect(children).toHaveLength(2);
      expect(children).toContain('User');
      expect(children).toContain('Admin');
    });

    it('should return empty array when no children', () => {
      OpenAPISchemaRegistry.registerSchema('Orphan', { type: 'object' });

      const children = OpenAPISchemaRegistry.getChildSchemas('Orphan');

      expect(children).toHaveLength(0);
    });
  });

  describe('registerSecurityScheme', () => {
    it('should register a security scheme', () => {
      const scheme = {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      };

      OpenAPISchemaRegistry.registerSecurityScheme('bearerAuth', scheme);

      const all = OpenAPISchemaRegistry.getAllSecuritySchemes();
      expect(all['bearerAuth']).toEqual(scheme);
    });
  });

  describe('registerSecuritySchemes', () => {
    it('should register multiple security schemes', () => {
      const schemes = {
        bearerAuth: { type: 'http', scheme: 'bearer' },
        apiKey: { type: 'apiKey', in: 'header', name: 'X-API-Key' },
      };

      OpenAPISchemaRegistry.registerSecuritySchemes(schemes);

      const all = OpenAPISchemaRegistry.getAllSecuritySchemes();
      expect(Object.keys(all)).toHaveLength(2);
    });
  });

  describe('unregisterSecurityScheme', () => {
    it('should remove a registered security scheme', () => {
      OpenAPISchemaRegistry.registerSecurityScheme('auth', { type: 'http' });
      expect(OpenAPISchemaRegistry.hasSecurityScheme('auth')).toBe(true);

      const result = OpenAPISchemaRegistry.unregisterSecurityScheme('auth');

      expect(result).toBe(true);
      expect(OpenAPISchemaRegistry.hasSecurityScheme('auth')).toBe(false);
    });

    it('should return false for non-existent scheme', () => {
      const result =
        OpenAPISchemaRegistry.unregisterSecurityScheme('NonExistent');
      expect(result).toBe(false);
    });
  });

  describe('getSecurityScheme', () => {
    it('should return a registered security scheme', () => {
      const scheme = { type: 'http', scheme: 'bearer' };
      OpenAPISchemaRegistry.registerSecurityScheme('auth', scheme);

      expect(OpenAPISchemaRegistry.getSecurityScheme('auth')).toEqual(scheme);
    });

    it('should return undefined for non-existent scheme', () => {
      expect(
        OpenAPISchemaRegistry.getSecurityScheme('NonExistent'),
      ).toBeUndefined();
    });
  });

  describe('hasSecurityScheme', () => {
    it('should return true for registered scheme', () => {
      OpenAPISchemaRegistry.registerSecurityScheme('auth', { type: 'http' });
      expect(OpenAPISchemaRegistry.hasSecurityScheme('auth')).toBe(true);
    });

    it('should return false for non-existent scheme', () => {
      expect(OpenAPISchemaRegistry.hasSecurityScheme('NonExistent')).toBe(
        false,
      );
    });
  });

  describe('clear', () => {
    it('should clear all schemas and security schemes', () => {
      OpenAPISchemaRegistry.registerSchema('Test', { type: 'string' });
      OpenAPISchemaRegistry.registerSecurityScheme('auth', { type: 'http' });

      OpenAPISchemaRegistry.clear();

      expect(OpenAPISchemaRegistry.schemaCount).toBe(0);
      expect(OpenAPISchemaRegistry.getAllSchemas()).toEqual({});
      expect(OpenAPISchemaRegistry.getAllSecuritySchemes()).toEqual({});
    });
  });

  describe('clearAutoGenerated', () => {
    it('should only clear auto-generated schemas', () => {
      OpenAPISchemaRegistry.registerSchema('Manual', { type: 'object' });
      OpenAPISchemaRegistry.registerSchema(
        'Auto1',
        { type: 'object' },
        { autoGenerated: true },
      );
      OpenAPISchemaRegistry.registerSchema(
        'Auto2',
        { type: 'object' },
        { autoGenerated: true },
      );

      OpenAPISchemaRegistry.clearAutoGenerated();

      expect(OpenAPISchemaRegistry.hasSchema('Manual')).toBe(true);
      expect(OpenAPISchemaRegistry.hasSchema('Auto1')).toBe(false);
      expect(OpenAPISchemaRegistry.hasSchema('Auto2')).toBe(false);
    });
  });

  describe('securitySchemeCount', () => {
    it('should return the count of security schemes', () => {
      expect(OpenAPISchemaRegistry.securitySchemeCount).toBe(0);

      OpenAPISchemaRegistry.registerSecurityScheme('auth1', { type: 'http' });
      OpenAPISchemaRegistry.registerSecurityScheme('auth2', { type: 'apiKey' });

      expect(OpenAPISchemaRegistry.securitySchemeCount).toBe(2);
    });
  });

  describe('validateSchemaReferences', () => {
    it('should return empty array when all references are valid', () => {
      OpenAPISchemaRegistry.registerSchema('Address', { type: 'object' });
      OpenAPISchemaRegistry.registerSchema('User', {
        type: 'object',
        properties: {
          address: { $ref: '#/components/schemas/Address' },
        },
      });

      const unresolved = OpenAPISchemaRegistry.validateSchemaReferences();

      expect(unresolved).toHaveLength(0);
    });

    it('should return unresolved references', () => {
      OpenAPISchemaRegistry.registerSchema('User', {
        type: 'object',
        properties: {
          address: { $ref: '#/components/schemas/Address' },
          company: { $ref: '#/components/schemas/Company' },
        },
      });

      const unresolved = OpenAPISchemaRegistry.validateSchemaReferences();

      expect(unresolved).toContain('Address');
      expect(unresolved).toContain('Company');
    });

    it('should handle nested references', () => {
      OpenAPISchemaRegistry.registerSchema('User', {
        type: 'object',
        properties: {
          posts: {
            type: 'array',
            items: { $ref: '#/components/schemas/Post' },
          },
        },
      });

      const unresolved = OpenAPISchemaRegistry.validateSchemaReferences();

      expect(unresolved).toContain('Post');
    });

    it('should not duplicate unresolved references', () => {
      OpenAPISchemaRegistry.registerSchema('User', {
        type: 'object',
        properties: {
          address1: { $ref: '#/components/schemas/Address' },
          address2: { $ref: '#/components/schemas/Address' },
        },
      });

      const unresolved = OpenAPISchemaRegistry.validateSchemaReferences();

      expect(unresolved.filter((r) => r === 'Address')).toHaveLength(1);
    });
  });

  describe('getSchemaNames', () => {
    it('should return all schema names', () => {
      OpenAPISchemaRegistry.registerSchema('User', { type: 'object' });
      OpenAPISchemaRegistry.registerSchema('Post', { type: 'object' });

      const names = OpenAPISchemaRegistry.getSchemaNames();

      expect(names).toContain('User');
      expect(names).toContain('Post');
    });
  });

  describe('getSecuritySchemeNames', () => {
    it('should return all security scheme names', () => {
      OpenAPISchemaRegistry.registerSecurityScheme('bearer', { type: 'http' });
      OpenAPISchemaRegistry.registerSecurityScheme('apiKey', {
        type: 'apiKey',
      });

      const names = OpenAPISchemaRegistry.getSecuritySchemeNames();

      expect(names).toContain('bearer');
      expect(names).toContain('apiKey');
    });
  });

  describe('CommonSchemas', () => {
    it('should have ErrorResponse schema', () => {
      expect(CommonSchemas.ErrorResponse).toBeDefined();
      expect(CommonSchemas.ErrorResponse.type).toBe('object');
      expect(
        (CommonSchemas.ErrorResponse.properties as Record<string, unknown>)
          .error,
      ).toBeDefined();
    });

    it('should have ValidationError schema', () => {
      expect(CommonSchemas.ValidationError).toBeDefined();
      expect(CommonSchemas.ValidationError.type).toBe('object');
    });

    it('should have PaginatedResponse schema', () => {
      expect(CommonSchemas.PaginatedResponse).toBeDefined();
      expect(CommonSchemas.PaginatedResponse.type).toBe('object');
      expect(
        (CommonSchemas.PaginatedResponse.properties as Record<string, unknown>)
          .items,
      ).toBeDefined();
      expect(
        (CommonSchemas.PaginatedResponse.properties as Record<string, unknown>)
          .pagination,
      ).toBeDefined();
    });
  });

  describe('CommonSecuritySchemes', () => {
    it('should have bearerAuth scheme', () => {
      expect(CommonSecuritySchemes.bearerAuth).toBeDefined();
      expect(CommonSecuritySchemes.bearerAuth.type).toBe('http');
      expect(CommonSecuritySchemes.bearerAuth.scheme).toBe('bearer');
    });

    it('should have apiKey scheme', () => {
      expect(CommonSecuritySchemes.apiKey).toBeDefined();
      expect(CommonSecuritySchemes.apiKey.type).toBe('apiKey');
      expect(CommonSecuritySchemes.apiKey.in).toBe('header');
    });
  });
});
