/**
 * @fileoverview OpenAPI schema registry for component schemas.
 * Provides a centralized place to register and retrieve OpenAPI schemas.
 * Supports schema validation, removal, and inheritance tracking.
 * @module openapi/schemas
 */

/**
 * Schema definition with optional metadata.
 */
export interface SchemaDefinition {
  /** The OpenAPI schema object */
  schema: Record<string, unknown>;
  /** Optional description of the schema */
  description?: string;
  /** Optional parent schema name for inheritance tracking */
  parent?: string;
  /** Whether this schema was auto-generated from decorators */
  autoGenerated?: boolean;
}

/**
 * Registry for OpenAPI component schemas.
 * Schemas are referenced by name in route metadata and resolved here.
 */
class OpenAPISchemaRegistryClass {
  private schemas: Map<string, SchemaDefinition> = new Map();
  private securitySchemes: Map<string, Record<string, unknown>> = new Map();

  /**
   * Register a schema.
   * @param name - Schema name (used in $ref)
   * @param schema - OpenAPI schema object
   * @param options - Optional metadata for the schema
   */
  registerSchema(
    name: string,
    schema: Record<string, unknown>,
    options?: {
      description?: string;
      parent?: string;
      autoGenerated?: boolean;
    },
  ): void {
    this.schemas.set(name, {
      schema,
      description: options?.description,
      parent: options?.parent,
      autoGenerated: options?.autoGenerated,
    });
  }

  /**
   * Register multiple schemas at once.
   * @param schemas - Object mapping schema names to schema definitions
   */
  registerSchemas(schemas: Record<string, Record<string, unknown>>): void {
    for (const [name, schema] of Object.entries(schemas)) {
      this.schemas.set(name, { schema });
    }
  }

  /**
   * Unregister a schema.
   * @param name - Schema name to remove
   * @returns True if the schema was removed, false if it didn't exist
   */
  unregisterSchema(name: string): boolean {
    return this.schemas.delete(name);
  }

  /**
   * Get a schema by name.
   * @param name - Schema name
   * @returns The schema or undefined
   */
  getSchema(name: string): Record<string, unknown> | undefined {
    return this.schemas.get(name)?.schema;
  }

  /**
   * Get a schema definition with metadata.
   * @param name - Schema name
   * @returns The schema definition or undefined
   */
  getSchemaDefinition(name: string): SchemaDefinition | undefined {
    return this.schemas.get(name);
  }

  /**
   * Get all registered schemas.
   * @returns Object mapping schema names to definitions
   */
  getAllSchemas(): Record<string, Record<string, unknown>> {
    const result: Record<string, Record<string, unknown>> = {};
    for (const [name, def] of this.schemas) {
      result[name] = def.schema;
    }
    return result;
  }

  /**
   * Get all schema definitions with metadata.
   * @returns Object mapping schema names to full definitions
   */
  getAllSchemaDefinitions(): Record<string, SchemaDefinition> {
    const result: Record<string, SchemaDefinition> = {};
    for (const [name, def] of this.schemas) {
      result[name] = def;
    }
    return result;
  }

  /**
   * Get schemas that inherit from a parent schema.
   * @param parentName - Parent schema name
   * @returns Array of child schema names
   */
  getChildSchemas(parentName: string): string[] {
    const children: string[] = [];
    for (const [name, def] of this.schemas) {
      if (def.parent === parentName) {
        children.push(name);
      }
    }
    return children;
  }

  /**
   * Register a security scheme.
   * @param name - Security scheme name
   * @param scheme - OpenAPI security scheme object
   */
  registerSecurityScheme(name: string, scheme: Record<string, unknown>): void {
    this.securitySchemes.set(name, scheme);
  }

  /**
   * Register multiple security schemes at once.
   * @param schemes - Object mapping scheme names to definitions
   */
  registerSecuritySchemes(
    schemes: Record<string, Record<string, unknown>>,
  ): void {
    for (const [name, scheme] of Object.entries(schemes)) {
      this.securitySchemes.set(name, scheme);
    }
  }

  /**
   * Unregister a security scheme.
   * @param name - Security scheme name to remove
   * @returns True if the scheme was removed, false if it didn't exist
   */
  unregisterSecurityScheme(name: string): boolean {
    return this.securitySchemes.delete(name);
  }

  /**
   * Get a security scheme by name.
   * @param name - Security scheme name
   * @returns The security scheme or undefined
   */
  getSecurityScheme(name: string): Record<string, unknown> | undefined {
    return this.securitySchemes.get(name);
  }

  /**
   * Get all registered security schemes.
   * @returns Object mapping scheme names to definitions
   */
  getAllSecuritySchemes(): Record<string, Record<string, unknown>> {
    const result: Record<string, Record<string, unknown>> = {};
    for (const [name, scheme] of this.securitySchemes) {
      result[name] = scheme;
    }
    return result;
  }

  /**
   * Clear all registrations (useful for testing).
   */
  clear(): void {
    this.schemas.clear();
    this.securitySchemes.clear();
  }

  /**
   * Clear only auto-generated schemas.
   * Useful when re-scanning decorated classes.
   */
  clearAutoGenerated(): void {
    for (const [name, def] of this.schemas) {
      if (def.autoGenerated) {
        this.schemas.delete(name);
      }
    }
  }

  /**
   * Get count of registered schemas.
   */
  get schemaCount(): number {
    return this.schemas.size;
  }

  /**
   * Get count of registered security schemes.
   */
  get securitySchemeCount(): number {
    return this.securitySchemes.size;
  }

  /**
   * Check if a schema is registered.
   * @param name - Schema name
   * @returns True if the schema is registered
   */
  hasSchema(name: string): boolean {
    return this.schemas.has(name);
  }

  /**
   * Check if a security scheme is registered.
   * @param name - Security scheme name
   * @returns True if the security scheme is registered
   */
  hasSecurityScheme(name: string): boolean {
    return this.securitySchemes.has(name);
  }

  /**
   * Validate that all schema references can be resolved.
   * @returns Array of unresolved schema references
   */
  validateSchemaReferences(): string[] {
    const unresolvedRefs: string[] = [];

    for (const [, def] of this.schemas) {
      const refs = this.extractSchemaRefs(def.schema);
      for (const ref of refs) {
        if (!this.schemas.has(ref)) {
          unresolvedRefs.push(ref);
        }
      }
    }

    return [...new Set(unresolvedRefs)];
  }

  /**
   * Extract schema references from a schema object.
   * @param schema - Schema object to scan
   * @returns Array of referenced schema names
   */
  private extractSchemaRefs(schema: Record<string, unknown>): string[] {
    const refs: string[] = [];

    const scan = (obj: unknown): void => {
      if (!obj || typeof obj !== 'object') {
        return;
      }

      if (Array.isArray(obj)) {
        obj.forEach(scan);
        return;
      }

      const record = obj as Record<string, unknown>;

      // Check for $ref
      if (typeof record.$ref === 'string') {
        const match = record.$ref.match(/^#\/components\/schemas\/(.+)$/);
        if (match) {
          refs.push(match[1]);
        }
      }

      // Recursively scan properties
      for (const value of Object.values(record)) {
        scan(value);
      }
    };

    scan(schema);
    return refs;
  }

  /**
   * Get all schema names.
   * @returns Array of registered schema names
   */
  getSchemaNames(): string[] {
    return Array.from(this.schemas.keys());
  }

  /**
   * Get all security scheme names.
   * @returns Array of registered security scheme names
   */
  getSecuritySchemeNames(): string[] {
    return Array.from(this.securitySchemes.keys());
  }
}

/**
 * Singleton instance of the schema registry.
 */
export const OpenAPISchemaRegistry = new OpenAPISchemaRegistryClass();

/**
 * Common schemas that are typically needed.
 * Applications can register these or define their own.
 */
export const CommonSchemas: Record<string, Record<string, unknown>> = {
  ErrorResponse: {
    type: 'object',
    properties: {
      error: {
        type: 'object',
        properties: {
          code: { type: 'string' },
          message: { type: 'string' },
          details: { type: 'object' },
          requestId: { type: 'string' },
          timestamp: { type: 'string', format: 'date-time' },
        },
        required: ['code', 'message'],
      },
    },
  },
  ValidationError: {
    type: 'object',
    properties: {
      error: {
        type: 'object',
        properties: {
          code: { type: 'string', example: 'VALIDATION_ERROR' },
          message: { type: 'string' },
          fields: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                field: { type: 'string' },
                message: { type: 'string' },
                value: {},
              },
              required: ['field', 'message'],
            },
          },
        },
        required: ['code', 'message'],
      },
    },
  },
  PaginatedResponse: {
    type: 'object',
    properties: {
      items: {
        type: 'array',
        items: {},
      },
      pagination: {
        type: 'object',
        properties: {
          page: { type: 'integer', minimum: 1 },
          pageSize: { type: 'integer', minimum: 1 },
          total: { type: 'integer', minimum: 0 },
          totalPages: { type: 'integer', minimum: 0 },
        },
        required: ['page', 'pageSize', 'total', 'totalPages'],
      },
    },
    required: ['items', 'pagination'],
  },
};

/**
 * Common security schemes.
 */
export const CommonSecuritySchemes: Record<string, Record<string, unknown>> = {
  bearerAuth: {
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT',
    description: 'JWT authentication token',
  },
  apiKey: {
    type: 'apiKey',
    in: 'header',
    name: 'X-API-Key',
    description: 'API key authentication',
  },
};
